import React, { useState } from 'react';
import {
  ShieldCheck,
  Eye,
  Lock,
  Calendar,
  User,
} from 'lucide-react';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  Table,
  TableHead,
  TableRow,
  TableHeader,
  TableBody,
  TableCell,
} from '@/components/ui/table';
import {
  Select,
  SelectTrigger,
  SelectContent,
  SelectItem,
  SelectValue,
} from '@/components/ui/select';
import { Separator } from '@/components/ui/separator';

/* 🔐 MOCK AUDIT DATA – BACKEND WILL REPLACE */
const payrollAuditLogs = [
  {
    id: 'AUD-001',
    month: 'January',
    year: '2026',
    generatedBy: 'Admin-HYD',
    generatedAt: '2026-02-01 10:45 AM',
    lockedBy: 'Admin-HYD',
    lockedAt: '2026-02-01 06:30 PM',
    employeesProcessed: 42,
    totalGross: 3850000,
    totalDeductions: 720000,
    totalNetPay: 3130000,
    status: 'LOCKED',
  },
  {
    id: 'AUD-002',
    month: 'February',
    year: '2026',
    generatedBy: 'Admin-HYD',
    generatedAt: '2026-03-01 11:10 AM',
    lockedBy: null,
    lockedAt: null,
    employeesProcessed: 44,
    totalGross: 4010000,
    totalDeductions: 760000,
    totalNetPay: 3250000,
    status: 'DRAFT',
  },
];

const months = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
];
const years = ['2025', '2026'];

const formatINR = (amount: number) =>
  new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(amount);

const PayrollAudit: React.FC = () => {
  const [month, setMonth] = useState('January');
  const [year, setYear] = useState('2026');

  const filteredLogs = payrollAuditLogs.filter(
    (p) => p.month === month && p.year === year
  );

  return (
    <div className="space-y-6 animate-fade-in">
      {/* HEADER */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2">
            <ShieldCheck className="h-6 w-6 text-primary" />
            Payroll Audit
          </h1>
          <p className="text-muted-foreground">
            Compliance & payroll activity review (Read-only)
          </p>
        </div>

        <div className="flex gap-2">
          <Select value={month} onValueChange={setMonth}>
            <SelectTrigger className="w-[140px]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {months.map((m) => (
                <SelectItem key={m} value={m}>
                  {m}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>

          <Select value={year} onValueChange={setYear}>
            <SelectTrigger className="w-[100px]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {years.map((y) => (
                <SelectItem key={y} value={y}>
                  {y}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>

      {/* AUDIT TABLE */}
      <Card>
        <CardHeader>
          <CardTitle>
            Payroll Audit Log – {month} {year}
          </CardTitle>
          <CardDescription>
            All payroll actions are system logged and immutable
          </CardDescription>
        </CardHeader>

        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Period</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead>Employees</TableHead>
                <TableHead>Net Pay</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Audit</TableHead>
              </TableRow>
            </TableHeader>

            <TableBody>
              {filteredLogs.map((log) => (
                <TableRow key={log.id}>
                  <TableCell>
                    <div className="font-medium">
                      {log.month} {log.year}
                    </div>
                    <div className="text-xs text-muted-foreground">
                      ID: {log.id}
                    </div>
                  </TableCell>

                  <TableCell>
                    <div className="flex items-center gap-1">
                      <User className="h-4 w-4" />
                      {log.generatedBy}
                    </div>
                    <div className="text-xs text-muted-foreground">
                      {log.generatedAt}
                    </div>
                  </TableCell>

                  <TableCell>
                    {log.employeesProcessed}
                  </TableCell>

                  <TableCell className="font-semibold">
                    {formatINR(log.totalNetPay)}
                  </TableCell>

                  <TableCell>
                    {log.status === 'LOCKED' ? (
                      <Badge className="badge-destructive">
                        <Lock className="h-3 w-3 mr-1" />
                        Locked
                      </Badge>
                    ) : (
                      <Badge className="badge-warning">
                        Draft
                      </Badge>
                    )}
                  </TableCell>

                  <TableCell>
                    <Button size="sm" variant="ghost">
                      <Eye className="h-4 w-4 mr-1" />
                      View
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>

          <Separator className="my-4" />

          <p className="text-xs text-muted-foreground">
            Audit logs are system-generated. No manual changes
            are allowed. Used for statutory, financial & internal
            audits.
          </p>
        </CardContent>
      </Card>
    </div>
  );
};

export default PayrollAudit;
